apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-migration-something
spec:
  source:
    path: test
    repoURL: 'https://github.com/leesei-tw/argocd-test.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process unless the `RespectIgnoreDifferences=true` sync option is enabled.
  ignoreDifferences:
    # for the specified json pointers
    - group: apps
      kind: Job
      jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name == "test").env[] | select(.name != "RUN_COUNT")
        - .spec.template.spec.containers[] | select(.name == "test").args[]