apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration-delete-job
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      serviceAccountName: delete-service-account
      containers:
        - name: data-migration-delete-job
          image: bitnami/kubectl:latest
          command:
            - kubectl
            - delete
            - job
            - data-migration-job
            - --ignore-not-found=true
      restartPolicy: Never
  backoffLimit: 0