apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration-job
  generateName: data-migration-job-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: data-migration
          image: perl:5.34.0
          args:
            - "ALL"
            - "TRUST"
          command: ["echo", "Welcome to my Java app"]
      restartPolicy: Never
  backoffLimit: 0