apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-resource-role
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["jobs"]
    verbs: ["delete"]