apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-resource-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: delete-service-account
roleRef:
  kind: Role
  name: delete-resource-role
  apiGroup: rbac.authorization.k8s.io