apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-resource-role
  namespace: default
  argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete"]